# This file was generated by GoReleaser. DO NOT EDIT.
class GitCloner < Formula
  desc "Git-cloner binary"
  homepage "https://gihub.com/lzecca78/git-cloner"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/lzecca78/git-cloner/releases/download/v0.1.0/git-cloner-darwin-amd64.tar.gz"
    sha256 "8a55d81af427261286a8af092785e2bac8f8dbc7d0982f20d5be10b02ad1a1fa"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/lzecca78/git-cloner/releases/download/v0.1.0/git-cloner-linux-amd64.tar.gz"
      sha256 "7fba9c20a975ed32b444949575b11a57a46c8a4978ef843a059e52e5a17c69ce"
    end
  end
  
  conflicts_with "git-cloner"

  def install
    bin.install 'git-cloner'
  end

  test do
    system "#{bin}/git-cloner"
  end
end
