# This file was generated by GoReleaser. DO NOT EDIT.
class GitCloner < Formula
  desc "Git-cloner binary"
  homepage "https://gihub.com/lzecca78/git-cloner"
  version "0.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/lzecca78/git-cloner/releases/download/v0.1.1/git-cloner-darwin-amd64.tar.gz"
    sha256 "de39b10d1189d42590c4333b83524816264fe94470501c88869b49bedb948c9e"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/lzecca78/git-cloner/releases/download/v0.1.1/git-cloner-linux-amd64.tar.gz"
      sha256 "0d0f8bf5fa7faa2b3f6bb84de7358cfd8cca26af22393616b9129ff0051421c7"
    end
  end
  
  conflicts_with "git-cloner"

  def install
    bin.install 'git-cloner'
  end

  test do
    system "#{bin}/git-cloner"
  end
end
