# This file was generated by GoReleaser. DO NOT EDIT.
class GitCloner < Formula
  desc "Git-cloner binary"
  homepage "https://gihub.com/lzecca78/git-cloner"
  version "0.64.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/lzecca78/git-cloner/releases/download/v0.64.0/git-cloner-darwin-amd64.tar.gz"
    sha256 "786d7f8ad517bdd872a8804b22027fd60bd9ebc03677ea3c9f4e56ac827f0723"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/lzecca78/git-cloner/releases/download/v0.64.0/git-cloner-linux-amd64.tar.gz"
      sha256 "2b56185117b49e444826d827500ed0544a86171263a8a3d1601e4074bb3d6dce"
    end
  end
  
  conflicts_with "git-cloner"

  def install
    bin.install 'git-cloner'
  end

  test do
    system "#{bin}/git-cloner"
  end
end
